/* lib.h: declare prototypes for functions in lib.a.
  Public domain. */

#ifndef LIB_LIB_H
#define LIB_LIB_H

#define FOPEN_W_MODE "w"
#define FOPEN_R_MODE "r"
#define FOPEN_WBIN_MODE "w"
#define FOPEN_RBIN_MODE "r"
#define DIR_SEP_STRING "/"

typedef enum kpse_filefmt {
    kpse_tex_format,
    kpse_mf_format,
    kpse_mp_format,
    kpse_fmt_format,
    kpse_vf_format,
    kpse_tfm_format,
    kpse_ocp_format,
    kpse_ofm_format,
    kpse_truetype_format,
    kpse_type1_format,
    kpse_opentype_format,
    kpse_fontmap_format,
    kpse_sfd_format,
    kpse_enc_format,
    kpse_miscfonts_format,
    kpse_web2c_format,
} kpse_file_format_type;

extern char *kpse_program_name;
extern bool kpse_make_tex_discard_errors;

void kpse_set_program_name(char *name);
const char *kpse_get_ext(kpse_file_format_type);
char *kpse_var_value(const char *name);

#define kpse_find_file(s,fmt,must_exist) mykpse_find_file(s, kpse_get_ext(fmt))

char *concat(const char *a, const char *b);
char *concat3(const char *a, const char *b, const char *c);

/* basechsuffix.c */
extern char * basenamechangesuffix (const char *, const char *, const char *);

/* chartostring.c */
extern char * chartostring (char);

/* eofeoln.c */
extern bool eof (FILE *);
extern bool eoln (FILE *);
extern void readln (FILE *);

/* fprintreal.c */
extern void fprintreal (FILE *, double, int, int);

/* inputint.c */
extern int inputint (FILE *);

/* input2int.c */
extern void zinput2ints (int *, int *);
extern void zinput3ints (int *, int *, int *);

/* main.c (or win32main.c or texmfmp.c) */
#ifndef NOT_WEB2C
/* Only used in Web2C programs and possibly harmful otherwise.  */
extern int argc;
extern char * *argv;
extern char * cmdline (int);
extern void mainbody (void); /* generated by web2c */
#endif

/* openclose.c */
extern bool open_input (FILE **, int, const char * fopen_mode);
extern bool open_output (FILE **, const char * fopen_mode);
extern bool open_input_with_dirname (FILE **, int, const char *);
extern void close_file (FILE *);
extern void recorder_change_filename (char *);
extern void recorder_record_input (const char *);
extern void recorder_record_output (const char *);

extern char * fullnameoffile;
extern bool recorder_enabled;
extern char * output_directory;

/* printversion.c */
extern void printversionandexit (const char *, const char *, const char *, const char *);

/* setupvar.c */
/* Set an array size from texmf.cnf.  */
extern void setupboundvariable (int *, const char *, int);

/* texmfmp.c */
extern bool texmf_yesno(const char *);

/* version.c */
extern const char *versionstring;

/* zround.c */
extern int zround (double);

#endif /* not LIB_LIB_H */
